[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dev-dependencies]
claims = "0.8"
fake = "5.1"
quickcheck = "1.1.0"
quickcheck_macros = "1.2.0"
tokio = { version = "1", features = ["macros", "rt"] }
wiremock = "0.6"
linkify = "0.11"

[dependencies]
actix-web = "4"
actix-web-flash-messages = { version = "0.5", features = ["cookies"] }
actix-session = { version = "0.11", features = ["redis-session-rustls"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
secrecy = { version = "0.10", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde-aux = "4.7"
serde_json = "1"
config = "0.15"
rand = { version = "0.10", features = ["std_rng"] }
uuid = { version = "1", features = ["v4", "serde"] }
urlencoding = "2"
htmlescape = "0.3"
tracing = { version = "0.1", features = ["log"] }
tracing-actix-web = "0.7"
tracing-log = "0.2"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
thiserror = "2"
anyhow = "1"
unicode-segmentation = "1.13"
validator = "0.20"
base64 = "0.22"
argon2 = { version = "0.5", features = ["std"] }

[dependencies.reqwest]
version = "0.13.2"
default-features = false
features = ["json", "rustls", "query", "form", "cookies"]

[dependencies.sqlx]
version = "0.8"
default-features = false
features = [
  "runtime-tokio-rustls",
  "macros",
  "postgres",
  "uuid",
  "chrono",
  "migrate",
]
