services:
  db:
    image: postgres:18
    container_name: zero2prod-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    container_name: zero2prod-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  zero2prod:
    container_name: zero2prod
    build:
      context: ..
    ports:
      - "8000:8000"
    environment:
      - APP_DATABASE__HOST=db
      - APP_DATABASE__PORT=5432
      - APP_DATABASE__REQUIRE_SSL=false
      - APP_APPLICATION__BASE_URL=127.0.0.1
      - APP_REDIS_URI=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://zero2prod:8000/health_check"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
