include:
  - ./../infra/docker-compose.yml

services:
  zero2prod:
    container_name: zero2prod
    build:
      context: ..
    ports:
      - "8000:8000"
    environment:
      - APP_DATABASE__HOST=db
      - APP_DATABASE__PORT=5432
      - APP_DATABASE__REQUIRE_SSL=false
    depends_on:
      db:
        condition: service_healthy
